# Generated by Django 4.0.4 on 2022-07-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date',)},
        ),
    ]
